import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const b=await chromium.connectOverCDP('http://127.0.0.1:9333'),p=await b.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('output/combat',{recursive:true});
try{await p.goto(process.argv[2]||'http://localhost:5180/?test');await p.waitForFunction(()=>window.__gameTest);await p.click('#start-btn');const report=await p.evaluate(()=>{
 const {game,world,g,step}=window.__gameTest,out=[];const ok=(name,value,detail)=>out.push({name,pass:!!value,detail});
 function fresh(){game.reset();game.start();game.player.invuln=0;game.enemies.forEach(e=>{e.alive=false;e.group.visible=false;});Object.assign(game.player,{x:0,y:0,z:30});game.camera.state.yaw=0;game.camera.state.pitch=-.02;game.camera.update(0,false,true);game.player.group.position.set(0,0,30);game.player.group.updateMatrixWorld(true);}
 fresh();game.combat.inventory[1].unlocked=true;game.combat.select(1);game.combat.state.cooldown=0;const near=game.ai.spawn(0,25,null,'shooter',true);game.combat.fire(g.camera);ok('scatter emits seven pellets for one shell',game.combat.bullets.length===7&&game.combat.inventory[1].ammo===7);for(let i=0;i<120;i++)game.combat.update(1/120);ok('scatter damages close enemy',near.hp<54,{hp:near.hp});
 fresh();game.combat.inventory[2].unlocked=true;game.combat.select(2);game.combat.state.cooldown=0;const a=game.ai.spawn(0,23,null,'shooter',true),c=game.ai.spawn(1.8,23,null,'shooter',true);game.combat.fire(g.camera);for(let i=0;i<160;i++)game.combat.update(1/120);ok('cannon splash damages multiple enemies',a.hp<54&&c.hp<54,{a:a.hp,c:c.hp});
 fresh();const protectedEnemy=game.ai.spawn(0,21,null,'shooter',true),wall=world.solid(0,23,5,.7,3,0xffffff);game.combat.explode(g.camera.position.clone().set(0,1,24),5,90,game.player);ok('cover blocks explosion damage',protectedEnemy.hp===54);wall.active=false;wall.group.visible=false;
 fresh();Object.assign(game.player,{x:-20,y:0,z:8.1});game.camera.state.yaw=0;game.camera.state.pitch=0;game.camera.update(0,false,true);game.player.group.position.set(-20,0,8.1);game.player.group.updateMatrixWorld(true);game.combat.fire(g.camera);ok('gun inside wall does not spawn a through-wall bullet',game.combat.bullets.length===0&&game.combat.inventory[0].ammo===23);
 fresh();const barrel=world.props.find(s=>s.type==='barrel'),blockedEnemy=game.ai.spawn(-23,16,null,'shooter',true),cover=world.solid(-24.5,16,.5,4,3,0xffffff);game.combat.destroy(barrel,100,game.player);ok('barrel blast respects intervening cover',blockedEnemy.hp===54);cover.active=false;cover.group.visible=false;
 fresh();game.combat.inventory[0].ammo=0;game.combat.inventory[0].reserve=0;const empty=game.combat.fire(g.camera);ok('empty gun with no reserve cannot shoot or reload',!empty&&game.combat.state.reloading===0&&game.combat.bullets.length===0);
 fresh();game.combat.inventory[0].ammo=2;game.combat.reload();game.combat.inventory[1].unlocked=true;game.combat.select(1);ok('switch cancels reload without transferring ammo',game.combat.state.reloading===0&&game.combat.inventory[0].ammo===2&&game.combat.inventory[1].ammo===8);
 fresh();for(let i=0;i<180;i++){game.combat.state.cooldown=0;game.combat.inventory[0].ammo=24;game.combat.fire(g.camera);}ok('projectile cap bounded',game.combat.bullets.length===110);for(let i=0;i<20;i++)game.combat.burst(g.camera.position,0xff0000,30);ok('particle cap bounded',game.combat.particles.length===140);
 fresh();const underfoot=world.props.find(s=>s.type==='crate');Object.assign(game.player,{x:(underfoot.x0+underfoot.x1)/2,z:(underfoot.z0+underfoot.z1)/2,y:underfoot.y1,grounded:true,vx:0,vz:0});game.combat.destroy(underfoot,100,game.player);step(1/120);ok('destroyed support falls with gravity rather than snapping',!game.player.grounded&&game.player.y>1&&game.player.vy<0);const warning=world.props.find(s=>s.type==='barrel');game.combat.destroy(warning,100,game.player);ok('destroyed barrel warning hides',!warning.label.visible);game.reset();ok('reset restores breakable warnings',warning.label.visible);
 fresh();game.player.hp=4;const shooter=game.ai.spawn(0,24,null,'shooter',true);game.combat.enemyFire(shooter);game.combat.enemyFire(shooter);let deathError=null;try{for(let i=0;i<120;i++)game.combat.update(1/120);}catch(e){deathError=e.message;}ok('lethal projectile safely clears effects during iteration',!deathError&&!game.player.alive&&game.combat.bullets.length===0,{deathError});step(1.5);ok('projectile death safely respawns',game.player.alive&&game.player.hp===100);
 fresh();for(const h of [0,.1,.5,1]){game.player.recoil=h;game.player.body.scale.setScalar(1);game.player.gun.scale.setScalar(1);}ok('character body retains original scale',game.player.body.scale.x===1&&game.player.body.scale.y===1&&game.player.body.scale.z===1);return out;
 });fs.writeFileSync('output/combat/report.json',JSON.stringify({report,errors},null,2));console.log(JSON.stringify(report,null,2));assert.deepEqual(report.filter(r=>!r.pass),[]);assert.deepEqual(errors,[]);await p.screenshot({path:'output/combat/gameplay.png'});console.log('PASS combat',report.length);}finally{await p.close();await b.close();}
