import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const browser=await chromium.connectOverCDP('http://127.0.0.1:9333'),checks=[];const url=process.argv[2]||pathToFileURL(process.cwd()+'/Bean-Frontier.html').href,remote=/^https?:/.test(url),out=remote?'output/pages':'output/offline';fs.mkdirSync(out,{recursive:true});
for(const mobile of [false,true]){
 const context=await browser.newContext({viewport:mobile?{width:844,height:390}:{width:1440,height:900},hasTouch:mobile,isMobile:mobile,offline:!remote}),page=await context.newPage(),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url())&&r.url()!==url)requests.push(r.url());});const check=(name,pass)=>{assert.ok(pass,name);checks.push({name:(mobile?'mobile ':'desktop ')+name,pass:!!pass});};
 try{await page.goto(url);await page.waitForFunction(()=>window.render_game_to_text);await page.waitForTimeout(500);check('no mutable game test interface',await page.evaluate(()=>typeof window.__gameTest==='undefined'));check('Chinese embedded font loads',await page.evaluate(async()=>{await document.fonts.ready;return document.fonts.check('900 24px "Noto Sans SC"','豆豆火力岛');}));
  if(mobile)await page.tap('#start-btn');else await page.click('#start-btn');await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).mode==='playing');await page.waitForTimeout(100);let s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('starts without network with running audio',s.mode==='playing'&&s.audio.context==='running'&&s.audio.playing);
  if(!mobile){await page.keyboard.down('KeyW');await page.waitForTimeout(350);await page.keyboard.up('KeyW');s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('normal clock movement',s.player.z<45);await page.keyboard.press('Space');await page.waitForTimeout(160);s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('normal clock jump',s.player.y>.4);await page.mouse.move(900,400);await page.mouse.down();await page.waitForTimeout(380);await page.mouse.up();s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('normal clock shooting consumes ammo',s.combat.shots>0);await page.keyboard.press('KeyR');await page.waitForTimeout(1150);s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('reload finishes',s.combat.inventory[0].ammo===24&&s.combat.reloading===0);await page.keyboard.press('Escape');}else await page.tap('#pause');
  s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('pause suspends audio',s.mode==='paused'&&!s.audio.playing);if(mobile)await page.tap('#resume');else await page.click('#resume');await page.waitForTimeout(100);check('resume plays',await page.evaluate(()=>JSON.parse(window.render_game_to_text()).mode==='playing'));
  await page.screenshot({path:out+'/'+(mobile?'mobile':'desktop')+'.png'});
  if(!mobile){await page.keyboard.press('KeyF');await page.waitForTimeout(100);check('fullscreen works',await page.evaluate(()=>!!document.fullscreenElement));await page.evaluate(()=>document.exitFullscreen());}else{check('mobile default fullscreen',await page.evaluate(()=>!!document.fullscreenElement));}
  if(mobile)await page.tap('#pause');else await page.click('#pause');if(mobile)await page.tap('#restart');else await page.click('#restart');await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).mode==='playing');s=await page.evaluate(()=>JSON.parse(window.render_game_to_text()));check('restart resets campaign',s.kills===0&&s.camps.every(c=>!c.cleared)&&s.challenges.every(c=>!c.complete)&&!s.combat.inventory[1].unlocked);
  check('no remote resources requested',requests.length===0);check('zero browser errors',errors.length===0);
 }finally{await context.close();}
}
await browser.close();fs.writeFileSync(out+'/report.json',JSON.stringify(checks,null,2));console.log(remote?'PASS Pages':'PASS offline',checks.length);
