import {THREE,C} from './gfx.js';
import {createBean,poseBean} from './character.js';
import {createCamera} from './camera.js';
import {createCombat,WEAPONS} from './combat.js';
import {createAI} from './ai.js';
import {GameAudio} from './audio.js';
import {moveActor,clamp,STEP} from './physics.js';
export function createGame(g,world){
 const player=createBean(g),enemies=[],audio=new GameAudio(),camera=createCamera(g,world,player);
 const state={mode:'ready',time:0,kills:0,respawns:0,respawn:0,checkpoint:{...world.spawn},challenge:null,completed:false,hit:0,hurt:0,toast:'',toastUntil:0,jumpBuffer:0,coyote:0,padCooldown:0};
 let input=null,onMode=()=>{};
 function notify(text){state.toast=text;state.toastUntil=state.time+3.2;}
 const combat=createCombat({g,world,player,enemies,getTime:()=>state.time,onEnemyDown:r=>{state.kills++;audio.tone(740,.12,'triangle');if(r.camp!==null){const c=world.camps[r.camp];if(!c.cleared&&enemies.filter(e=>e.camp===c.id).every(e=>!e.alive)){c.cleared=true;c.banner.material=g.mat(C.mint);state.checkpoint={x:c.x,y:c.y,z:c.z};player.hp=Math.min(100,player.hp+30);notify(c.name+'已清理 · 解锁安全重生点');combat.burst(new THREE.Vector3(c.x,c.y+3,c.z),C.yellow,35);}}},onHit:kill=>{state.hit=kill?.24:.12;audio.tone(kill?880:650,.055,'triangle',.045);},onPlayerHurt:()=>{state.hurt=.45;audio.tone(140,.12,'triangle');if(player.hp<=0)down();},notify});
 const ai=createAI(g,world,player,enemies);
 function mode(value){state.mode=value;input?.reset();audio.setPlaying(value==='playing');onMode(value);}
 function reset(){input?.reset();world.reset();combat.reset();ai.populate();camera.reset();Object.assign(state,{mode:'ready',time:0,kills:0,respawns:0,respawn:0,checkpoint:{...world.spawn},challenge:null,completed:false,hit:0,hurt:0,toast:'',toastUntil:0,jumpBuffer:0,coyote:0,padCooldown:0});Object.assign(player,{...world.spawn,vx:0,vy:0,vz:0,yaw:0,hp:100,maxHp:100,alive:true,grounded:true,invuln:2,kx:0,kz:0,recoil:0});player.group.visible=true;poseBean(player,0,true);audio.reset();audio.setPlaying(false);onMode('ready');camera.update(0,true);}
 function start(fresh=false){if(fresh)reset();if(state.mode!=='ready'&&state.mode!=='paused'&&state.mode!=='complete')return;audio.unlock().then(()=>audio.setPlaying(state.mode==='playing'));mode('playing');camera.update(0,false,true);notify('欢迎上岛 · 前方金色装备台有泡泡散射枪');}
 function pause(){if(state.mode==='playing'){mode('paused');if(document.pointerLockElement)document.exitPointerLock();}else if(state.mode==='paused'){mode('playing');camera.update(0,false,true);}}
 function down(){if(state.respawn>0)return;player.alive=false;player.group.visible=false;state.respawn=1.3;state.respawns++;input?.reset();combat.clearEffects();notify('泡泡破了！正在安全点重生…');}
 function respawn(){Object.assign(player,{...state.checkpoint,vx:0,vy:0,vz:0,kx:0,kz:0,hp:100,alive:true,grounded:true,invuln:2.5});player.group.visible=true;for(let i=0;i<3;i++)if(combat.inventory[i].unlocked){combat.inventory[i].ammo=WEAPONS[i].mag;combat.inventory[i].reserve=Math.max(combat.inventory[i].reserve,WEAPONS[i].mag*2);}combat.state.reloading=0;camera.update(0,false,true);notify('安全重生 · 本局武器与目标进度保留');}
 function nearestInteraction(){if(!player.alive)return null;let best=null,d=2.8;for(const o of [...world.flags,...world.pickups.filter(p=>p.type==='weapon'&&p.active)]){const n=Math.hypot(o.x-player.x,o.z-player.z);if(n<d&&Math.abs(o.y-player.y)<2){best=o;d=n;}}return best;}
 function stopChallenge(){if(!state.challenge)return;for(const o of [...world.targets,...world.coins]){o.active=false;o.group.visible=false;}ai.removeChallenge();state.challenge=null;}
 function beginChallenge(flag){stopChallenge();const duration=flag.id==='targets'?35:flag.id==='collect'?50:55;state.challenge={id:flag.id,time:duration,total:flag.id==='targets'?6:flag.id==='collect'?8:3,progress:0};if(flag.id==='targets')for(const t of world.targets){t.active=true;t.group.visible=true;}if(flag.id==='collect')for(const c of world.coins){c.active=true;c.group.visible=true;}if(flag.id==='combat'){for(const [i,x,z] of [[0,10,-49],[1,15,-45],[2,10,-37]])ai.spawn(x,z,null,i===1?'charger':'shooter',true);}notify(flag.name+'开始 · '+duration+' 秒');}
 function interact(){const o=nearestInteraction();if(!o)return;if(o.type==='weapon'){combat.inventory[o.weapon].unlocked=true;o.active=false;o.group.visible=false;if(o.label)o.label.visible=false;combat.select(o.weapon);notify('获得'+WEAPONS[o.weapon].name+' · 已装备');audio.tone(960,.15);return;}beginChallenge(o);}
 function completeChallenge(){const f=world.flags.find(f=>f.id===state.challenge.id);f.complete=true;f.banner.material=g.mat(C.mint);notify(f.name+'挑战完成！');combat.burst(new THREE.Vector3(f.x,f.y+2,f.z),C.yellow,35);player.hp=Math.min(100,player.hp+25);stopChallenge();}
 function action(id){if(id==='start'){start();return;}if(id==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});return;}if(state.mode!=='playing')return;if(id==='jump')state.jumpBuffer=.13;if(id==='reload')combat.reload();if(id==='interact')interact();if(id.startsWith('weapon'))combat.select(Number(id.slice(-1)));}
 function update(dt){if(state.mode!=='playing'){camera.update(dt,state.mode==='ready');return;}state.time+=dt;state.hit=Math.max(0,state.hit-dt);state.hurt=Math.max(0,state.hurt-dt);state.padCooldown=Math.max(0,state.padCooldown-dt);player.invuln=Math.max(0,player.invuln-dt);
  if(state.respawn>0){state.respawn=Math.max(0,state.respawn-dt);if(!state.respawn)respawn();}
  const controls=input?.sample()||{x:0,z:0,aim:false,sprint:false,fire:false};camera.state.aim=controls.aim;
  if(player.alive){const magnitude=Math.hypot(controls.x,controls.z),normal=Math.max(1,magnitude),speed=controls.aim?3.7:controls.sprint?9:6;
   const yaw=camera.state.yaw,dx=(Math.cos(yaw)*controls.x+Math.sin(yaw)*controls.z)/normal,dz=(Math.sin(yaw)*controls.x-Math.cos(yaw)*controls.z)/normal;
   player.kx*=Math.exp(-dt*9);player.kz*=Math.exp(-dt*9);const blend=1-Math.exp(-dt*24);player.vx+=(dx*speed-player.vx)*blend;player.vz+=(dz*speed-player.vz)*blend;player.vx+=player.kx*dt*8;player.vz+=player.kz*dt*8;
   state.coyote=player.grounded?.09:Math.max(0,state.coyote-dt);state.jumpBuffer=Math.max(0,state.jumpBuffer-dt);if(state.jumpBuffer>0&&state.coyote>0){player.vy=8.2;player.grounded=false;state.jumpBuffer=state.coyote=0;audio.tone(450,.06);}
   moveActor(player,dt,world);player.yaw=camera.state.yaw;player.recoil=Math.max(0,player.recoil-dt*8);poseBean(player,state.time,true);player.gun.rotation.x=camera.state.pitch-player.recoil*.1;
   if(player.y< -10)down();
   if(!state.padCooldown&&player.grounded)for(const pad of world.pads)if(Math.hypot(player.x-pad.x,player.z-pad.z)<1.1&&Math.abs(player.y-pad.y)<.15){player.vy=13;player.grounded=false;state.padCooldown=.6;audio.tone(600,.12);notify('弹跳！空中可继续移动和射击');break;}
   camera.update(dt,false);
   if(controls.fire&&combat.fire(g.camera,input?.mobile)){const w=WEAPONS[combat.state.weapon];audio.tone(w.explosive?115:combat.state.weapon===1?250:520,w.explosive?.14:.06,w.explosive?'triangle':'square',.022);}
  }
  ai.update(dt,state.time,combat);combat.update(dt);
  for(const p of world.pickups){if(!p.active&&p.type==='supply'&&state.time>=p.readyAt){p.active=true;p.group.visible=true;}if(!p.active)continue;p.group.children[1].rotation.y=state.time;p.group.children[1].position.y=Math.sin(state.time*2+p.x)*.12;
   if(p.type==='supply'&&player.alive&&Math.hypot(player.x-p.x,player.z-p.z)<1.6&&Math.abs(player.y-p.y)<1.5){const need=player.hp<100||combat.inventory.some((s,i)=>s.unlocked&&(s.ammo<WEAPONS[i].mag||s.reserve<WEAPONS[i].reserve));if(need){player.hp=100;combat.inventory.forEach((s,i)=>{if(s.unlocked){s.ammo=WEAPONS[i].mag;s.reserve=WEAPONS[i].reserve;}});combat.state.reloading=0;p.active=false;p.group.visible=false;p.readyAt=state.time+18;notify('补给充满 · 生命与弹药恢复');audio.tone(800,.1);}}
  }
  if(state.challenge){const c=state.challenge;c.time-=dt;if(c.id==='targets')c.progress=world.targets.filter(t=>!t.active).length;if(c.id==='combat')c.progress=enemies.filter(r=>r.challenge&&!r.alive).length;if(c.id==='collect'){for(const coin of world.coins){if(!coin.active)continue;coin.group.rotation.y=state.time*2;coin.group.position.y=coin.y+Math.sin(state.time*3)*.16;if(player.alive&&Math.hypot(player.x-coin.x,player.z-coin.z)<1.3&&Math.abs(player.y+1-coin.y)<2){coin.active=false;coin.group.visible=false;audio.tone(1000,.06);}}c.progress=world.coins.filter(v=>!v.active).length;}
   if(c.progress>=c.total)completeChallenge();else if(c.time<=0){stopChallenge();notify('挑战时间到 · 到旗帜旁可重新开始');}}
  if(!state.completed&&world.camps.every(c=>c.cleared)&&world.flags.every(f=>f.complete)){state.completed=true;mode('complete');if(document.pointerLockElement)document.exitPointerLock();}
 }
 function snapshot(){const round=v=>+v.toFixed(3);return {coordinateSystem:'x east, y height, z south; yaw 0 faces north (-z)',mode:state.mode,time:round(state.time),physicsHz:120,player:{x:round(player.x),y:round(player.y),z:round(player.z),hp:player.hp,alive:player.alive,grounded:player.grounded,vx:round(player.vx),vy:round(player.vy),vz:round(player.vz),invuln:round(player.invuln)},camera:{yaw:round(camera.state.yaw),pitch:round(camera.state.pitch),distance:round(camera.state.distance),position:{x:round(g.camera.position.x),y:round(g.camera.position.y),z:round(g.camera.position.z)},avatarOpacity:round(camera.state.avatarOpacity??1),aim:camera.state.aim,fov:round(g.camera.fov)},combat:{...combat.state,inventory:combat.inventory.map(s=>({...s}))},kills:state.kills,respawns:state.respawns,respawnIn:round(state.respawn),checkpoint:state.checkpoint,challenge:state.challenge?{...state.challenge,time:round(state.challenge.time)}:null,completed:state.completed,camps:world.camps.map(({id,name,x,y,z,cleared})=>({id,name,x,y,z,cleared,enemies:enemies.filter(e=>e.camp===id&&e.alive).length})),challenges:world.flags.map(({id,name,x,y,z,complete})=>({id,name,x,y,z,complete})),enemies:enemies.filter(e=>e.alive).map(e=>({id:e.id,type:e.type,camp:e.camp,challenge:e.challenge,x:round(e.x),y:round(e.y),z:round(e.z),hp:e.hp,mode:e.aiMode})),pickups:world.pickups.map(({type,weapon,x,y,z,active,readyAt})=>({type,weapon,x,y,z,active,readyAt})),props:world.props.map(s=>({type:s.type,x:(s.x0+s.x1)/2,z:(s.z0+s.z1)/2,hp:s.hp,active:s.active})),bullets:combat.bullets.length,particles:combat.particles.length,touch:input?{...input.state}:null,audio:audio.status(),interaction:nearestInteraction()?.name||nearestInteraction()?.type||null};}
 return {g,world,player,enemies,state,audio,camera,combat,ai,notify,mode,reset,start,pause,down,respawn,interact,beginChallenge,stopChallenge,action,update,snapshot,nearestInteraction,bindInput:value=>{input=value;},bindMode:fn=>{onMode=fn;}};
}
