import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {chromium} from 'playwright';
const url=process.argv[2]||pathToFileURL(path.resolve('Bean-Frontier.html')).href,offline=url.startsWith('file:'),out='output/'+(offline?'bomb-offline':'bomb-live');fs.mkdirSync(out,{recursive:true});const browser=await chromium.connectOverCDP('http://127.0.0.1:9333');const ctx=await browser.newContext({viewport:{width:1280,height:800}}),page=await ctx.newPage(),errors=[],requests=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));const read=()=>page.evaluate(()=>JSON.parse(render_game_to_text())),advance=ms=>page.evaluate(ms=>advanceTime(ms),ms),check=(name,pass,detail)=>{checks.push({name,pass:!!pass,detail});assert.ok(pass,name+' '+JSON.stringify(detail??''));console.log('PASS '+name);};
try{
 if(offline)await ctx.setOffline(true);await page.goto(url);await page.waitForFunction(()=>window.render_game_to_text);check('production build has no mutable test API',await page.evaluate(()=>!window.__gameTest));check('embedded fonts loaded',await page.evaluate(()=>document.fonts.check('900 24px "Noto Sans SC"')));await page.click('#side-defend');await page.click('#start-btn');await page.waitForFunction(()=>JSON.parse(render_game_to_text()).mode==='playing');let s=await read();check('defensive choice starts 5v5 buy round',s.phase==='buy'&&s.attackTeam===1&&s.actors.length===10);
 await page.click('#recommend');s=await read();check('offline purchasing works',s.player.money===200&&s.player.armor===100);await advance(15200);await page.waitForFunction(()=>document.querySelector('#buy-panel').classList.contains('hidden'));s=await read();check('offline active round starts',s.phase==='active'&&s.player.hp===100);
 await page.locator('#game').click({position:{x:640,y:450}});await page.mouse.down();await advance(700);await page.mouse.up();s=await read();check('offline hitscan fire consumes ammo',s.player.equipment[0].ammo<12);await page.keyboard.press('KeyR');await advance(1200);s=await read();check('offline reload',s.player.equipment[0].ammo===12&&s.player.equipment[0].reserve<60);
 await page.keyboard.down('KeyD');await advance(3600);await page.keyboard.up('KeyD');await advance(100);s=await read();check('offline movement',s.player.x< -4,s.player);await page.keyboard.down('KeyW');await advance(4000);await page.keyboard.up('KeyW');await advance(15000);s=await read();check('AI battle advances with local assets',s.time>30&&s.actors.some(a=>!a.alive));
 await page.keyboard.press('Escape');s=await read();check('offline pause clears input and music playback',s.mode==='paused'&&!s.touch.fire&&!s.touch.interactHeld&&!s.audio.playing);const frozen=s.time;await advance(1000);check('offline pause freezes simulation',(await read()).time===frozen);await page.click('#resume');check('offline resume',(await read()).mode==='playing');
 // Finish the current round normally and check unified next-round revival.
 for(let i=0;i<24;i++){s=await read();if(s.round>1)break;await advance(5000);}s=await read();check('offline round ends and all actors revive',s.round>=2&&s.player.hp===100&&s.player.alive,s);
 await page.click('#pause');await page.click('#restart');await page.waitForFunction(()=>JSON.parse(render_game_to_text()).mode==='playing');s=await read();check('offline fresh match resets scores/round/economy',s.round===1&&s.scores.every(x=>x===0)&&s.player.money===800&&s.player.equipment[1]===null,s.player);
 const audio=await page.evaluate(()=>{const A=window.AudioContext||window.webkitAudioContext;return !!A;});await page.waitForTimeout(200);s=await read();check('local synthesized audio unlocked',audio&&s.audio.context==='running'&&s.audio.playing&&s.audio.stepsScheduled>0,s.audio);
 if(offline){
  const fixture=await ctx.newPage();await fixture.goto(url+'?test');await fixture.waitForFunction(()=>window.__gameTest);await fixture.click('#start-btn');const death=await fixture.evaluate(()=>{advanceTime(15010);const {game}=__gameTest;game.combat.damage(game.player,100,game.enemies[0],true);return {alive:game.player.alive,carrier:game.state.bomb.carrierId,drop:game.state.drops.some(d=>d.type==='bomb'),spectate:game.state.spectateId};});check('offline packaged death drops bomb and selects spectator',!death.alive&&death.carrier===null&&death.drop&&death.spectate!==null,death);let revived=false;for(let i=0;i<28;i++){await fixture.evaluate(()=>advanceTime(5000));const f=await fixture.evaluate(()=>JSON.parse(render_game_to_text()));if(f.round>1&&f.player.alive){revived=true;break;}}check('offline packaged AI proceeds and dead player revives next round',revived);await fixture.close();check('no remote resource requests',requests.every(r=>!/^https?:/.test(r)),requests);
 }check('no browser errors',errors.length===0,errors);
}catch(e){console.error(e);process.exitCode=1;checks.push({error:e.stack});}finally{fs.writeFileSync(out+'/report.json',JSON.stringify({url,checks,errors,requests,final:await read().catch(()=>null)},null,2));await ctx.close();await browser.close();}
