import './style.css';
import {THREE,createGraphics} from './gfx.js';
import {createWorld} from './world.js';
import {createInput} from './input.js';
import {createGame} from './game.js';
import {STEP,clamp} from './physics.js';
import {WEAPONS} from './combat.js';
import * as characterDisplay from './character.js';
const $=s=>document.querySelector(s),mobile=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
try{await document.fonts.load('900 57px "Noto Sans SC"','豆豆火力岛爆破行动糖果竞技场');await document.fonts.ready;}catch{}
const g=createGraphics($('#game'),mobile),world=createWorld(g),game=createGame(g,world);
let helpOpen=false,buyOpen=false,chosenSide='attack',lastPhase='',lastRound=0,uiTime=-Infinity,settings={fps:mobile?30:60,assist:true};
const dir=new THREE.Vector3(),v=new THREE.Vector3();
function aimSlowdown(){if(!mobile||!settings.assist||!game.player.alive||game.state.mode!=='playing')return 1;g.camera.getWorldDirection(dir);for(const a of game.actors??game.enemies){if(!a.alive||a.team===game.player.team)continue;v.set(a.x,a.y+1.35,a.z).sub(g.camera.position);const distance=v.length();if(distance<32&&distance>1&&v.normalize().dot(dir)>.992&&!world.blocked(g.camera.position,{x:a.x,y:a.y+1.35,z:a.z},.01))return .65;}return 1;}
const input=createInput({canvas:$('#game'),onLook:(x,y)=>game.camera.look(x,y),onPause:()=>{if(game.state.mode==='playing')game.pause();},onAction:id=>{if(id==='fullscreen'){fullscreen();return;}if(id==='buy'){setBuy(!buyOpen);return;}if(id==='start'){launch();return;}game.action(id);},playing:()=>game.state.mode==='playing'&&!buyOpen,getScope:()=>game.camera.state.scope?'sniper':game.camera.state.aim?'ads':'look',aimSlowdown});game.bindInput(input);
function setBuy(open){buyOpen=!!open&&game.state.phase==='buy'&&game.state.mode==='playing';game.state.buyOpen=buyOpen;input.reset();$('#buy-panel')?.classList.toggle('hidden',!buyOpen);if(buyOpen&&document.pointerLockElement)document.exitPointerLock?.();}
function modeUI(){helpOpen=false;$('#help-copy')?.classList.add('hidden');$('#mobile-settings')?.classList.remove('hidden');const s=game.state;$('#lobby').classList.toggle('hidden',s.mode!=='ready');$('#hud').classList.toggle('hidden',s.mode==='ready');const modal=s.mode==='paused'||s.phase==='match_end';$('#modal').classList.toggle('hidden',!modal);if(s.mode!=='playing')setBuy(false);if(s.phase==='match_end'){$('#modal-title').textContent=s.scores[0]>=5?'胜利！糖果行动完成':'本场结束 · 下次再战';$('#modal-copy').textContent=`本场比分 ${s.scores[0]} : ${s.scores[1]}。重新开局可选择攻守。`;$('#resume').classList.add('hidden');}else{$('#modal-title').textContent='战术暂停';$('#modal-copy').textContent='对局与计时已暂停。调整操作后继续。';$('#resume').classList.remove('hidden');$('#resume').textContent='继续对局 ↗';}}
game.bindMode(modeUI);
function fullscreen(){if(document.fullscreenElement){document.exitFullscreen?.();return;}document.documentElement.requestFullscreen?.().catch(()=>{});}
async function enterMobileFullscreen(){if(!input.mobile)return;try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{}try{await screen.orientation?.lock?.('landscape');}catch{}g.resize();}
async function launch(fresh=false){game.audio.unlock();if(fresh)game.reset();await enterMobileFullscreen();game.start(chosenSide,false);lastPhase='';lastRound=0;updateUI(true);}
function bind(id,fn){const e=$('#'+id);if(e)e.onclick=fn;}
bind('start-btn',()=>launch());bind('side-attack',()=>{chosenSide='attack';$('#side-attack').classList.add('active');$('#side-defend').classList.remove('active');});bind('side-defend',()=>{chosenSide='defend';$('#side-defend').classList.add('active');$('#side-attack').classList.remove('active');});bind('pause',()=>game.pause());bind('resume',()=>{if(helpOpen){modeUI();return;}game.pause();});bind('help-btn',()=>{helpOpen=true;$('#modal').classList.remove('hidden');$('#modal-title').textContent='爆破行动指南';$('#modal-copy').textContent='先赢五回合。安包、守包、拆包，每一回合都能翻盘。';$('#help-copy')?.classList.remove('hidden');$('#mobile-settings')?.classList.add('hidden');$('#resume').classList.remove('hidden');$('#resume').textContent='知道了 ↗';});bind('restart',()=>launch(true));bind('home',()=>{game.reset();lastPhase='';lastRound=0;updateUI(true);});bind('full',fullscreen);bind('buy-open',()=>setBuy(true));bind('buy-close',()=>setBuy(false));bind('recommend',()=>game.buy('recommended'));bind('spectate-next',()=>game.action('spectate-next'));bind('spectate-speed',()=>game.action('speed'));
for(const b of document.querySelectorAll('[data-buy]'))b.onclick=()=>game.buy(b.dataset.buy==='armor'?'armor':Number(b.dataset.buy));
for(const b of document.querySelectorAll('[data-weapon]'))b.onclick=()=>game.action('weapon'+b.dataset.weapon);
bind('tactic-a',()=>game.setTactic('A'));bind('tactic-b',()=>game.setTactic('B'));
const settingKey='bean-frontier-settings';
function restoreSettings(){try{const saved=JSON.parse(localStorage.getItem(settingKey)||'{}');if(typeof saved.music==='boolean')game.audio.setMusic(saved.music);if(typeof saved.sound==='boolean')game.audio.setEffects(saved.sound);input.setSensitivity({look:saved.lookSensitivity??1,ads:saved.adsSensitivity??.6,sniper:saved.sniperSensitivity??.35});input.setLayout?.({size:saved.buttonSize??1,opacity:saved.buttonOpacity??.72});settings.fps=saved.fps===60?60:saved.fps===30?30:settings.fps;settings.assist=saved.assist!==false;}catch{}}
function saveSettings(){const sens=input.getSensitivity(),layout=input.getLayout?.()||{size:1,opacity:.72};try{localStorage.setItem(settingKey,JSON.stringify({music:game.audio.musicEnabled,sound:game.audio.effectsEnabled,lookSensitivity:sens.look,adsSensitivity:sens.ads,sniperSensitivity:sens.sniper,buttonSize:layout.size,buttonOpacity:layout.opacity,fps:settings.fps,assist:settings.assist}));}catch{}}
function settingsUI(){const sensitivity=input.getSensitivity(),layout=input.getLayout?.()||{size:1,opacity:.72};for(const [id,value] of [['camera-sensitivity',sensitivity.look],['ads-sensitivity',sensitivity.ads],['sniper-sensitivity',sensitivity.sniper],['button-size',layout.size],['button-opacity',layout.opacity]]){if($( '#'+id))$('#'+id).value=value;if($('#'+id+'-value'))$('#'+id+'-value').textContent=Math.round(value*100)+'%';}if($('#fps-setting'))$('#fps-setting').value=settings.fps;if($('#aim-assist'))$('#aim-assist').checked=settings.assist;$('#music').classList.toggle('off',!game.audio.musicEnabled);$('#sound').classList.toggle('off',!game.audio.effectsEnabled);}
for(const [id,key] of [['camera-sensitivity','look'],['ads-sensitivity','ads'],['sniper-sensitivity','sniper']])$('#'+id)?.addEventListener('input',e=>{input.setSensitivity({[key]:Number(e.target.value)});settingsUI();saveSettings();});
for(const [id,key] of [['button-size','size'],['button-opacity','opacity']])$('#'+id)?.addEventListener('input',e=>{input.setLayout?.({[key]:Number(e.target.value)});settingsUI();saveSettings();});
$('#fps-setting')?.addEventListener('change',e=>{settings.fps=Number(e.target.value)===60?60:30;saveSettings();});$('#aim-assist')?.addEventListener('change',e=>{settings.assist=e.target.checked;saveSettings();});
bind('music',()=>{game.audio.setMusic(!game.audio.musicEnabled);saveSettings();settingsUI();});bind('sound',()=>{game.audio.setEffects(!game.audio.effectsEnabled);saveSettings();settingsUI();});
const text=(id,value)=>{const el=$('#'+id);if(el)el.textContent=value;};
function map(){let svg='<svg viewBox="-29 -26 58 52" xmlns="http://www.w3.org/2000/svg"><rect x="-28" y="-25" width="56" height="50" rx="2" fill="#c5d6c0"/>';
 for(const s of world.solids)if(s.type!=='floor'&&s.type!=='trim')svg+=`<rect x="${s.x0}" y="${s.z0}" width="${s.x1-s.x0}" height="${s.z1-s.z0}" fill="#678b84"/>`;
 for(const s of world.sites)svg+=`<circle cx="${s.x}" cy="${s.z}" r="3.2" fill="${s.id==='A'?'#f5bb82':'#8bd4dd'}"/><text x="${s.x}" y="${s.z+1.6}" text-anchor="middle" fill="#284c50" font-size="4" font-weight="900">${s.id}</text>`;
 for(const a of game.actors??[])if(a.alive&&a.team===game.player.team&&a!==game.player)svg+=`<circle cx="${a.x}" cy="${a.z}" r="1.1" fill="#3c7dea" stroke="#fff" stroke-width=".35"/>`;
 const p=game.player.alive?game.player:(game.actors.find(a=>a.id===game.state.spectateId)||game.player);svg+=`<g transform="translate(${p.x} ${p.z}) rotate(${game.camera.state.yaw*180/Math.PI})"><path d="M0-2.2L1.5 1.4 0 .7-1.5 1.4Z" fill="#fff" stroke="#284c50" stroke-width=".4"/></g>`;
 const bomb=game.state.bomb;if(bomb?.planted)svg+=`<circle cx="${bomb.x}" cy="${bomb.z}" r="1.4" fill="#f455a6"/>`;else if(bomb&&bomb.carrierId==null&&bomb.x!=null)svg+=`<rect x="${bomb.x-.6}" y="${bomb.z-.6}" width="1.2" height="1.2" fill="#f455a6"/>`;svg+='</svg>';$('#map').innerHTML=svg;
}
function updateUI(force=false){const s=game.state,p=game.player;if(!force&&performance.now()-uiTime<60)return;uiTime=performance.now();
 if(s.phase!==lastPhase||s.round!==lastRound){modeUI();if(s.phase==='buy'){setBuy(true);}else setBuy(false);lastPhase=s.phase;lastRound=s.round;}
 const attack=p.team===s.attackTeam,remaining=Math.max(0,(s.phase==='planted'?s.bomb.explodesAt:s.phaseEndsAt??s.time)-s.time);text('score',`${s.scores?.[0]??0} : ${s.scores?.[1]??0}`);text('round-label',`第 ${s.round??1} 回合 · ${attack?'进攻':'防守'}`);text('timer',s.phase==='round_end'?'结算':`${Math.floor(Math.ceil(remaining)/60)}:${(Math.ceil(remaining)%60).toString().padStart(2,'0')}`);$('#timer')?.classList.toggle('danger',s.phase==='planted'||remaining<10);
 const actors=game.actors??[],viewed=p.alive?p:(actors.find(a=>a.id===s.spectateId)||p),friends=actors.filter(a=>a.team===p.team&&a.alive).length,foes=actors.filter(a=>a.team!==p.team&&a.alive).length;text('alive-count',`己方 ${friends} · 对方 ${foes}`);
 let objective=s.phase==='buy'?'准备购买 · 选择 A / B 战术':s.phase==='planted'?(attack?'炸弹已安放 · 守住包点':'炸弹已安放 · 按住互动拆除'):s.phase==='round_end'?((s.roundResult?(s.roundResult.winner===p.team?'本回合胜利':'本回合失利')+' · '+s.roundResult.reason:s.toast??'回合结束')):attack?'前往 A / B 包点 · 按住互动安包':`重点防守 ${s.tactic} 点 · 留意另一包点`;if(!p.alive&&s.phase!=='round_end')objective='已阵亡 · 观战队友';text('objective',objective);
 $('#health-fill').style.width=Math.max(0,viewed.hp)+'%';text('health-text',Math.ceil(viewed.hp));text('armor-text',viewed.armor?'护甲':'无护甲');text('money',`$ ${p.money??800}`);
 const equipped=viewed.equipment?.[viewed.slot??0],weapon=WEAPONS[equipped?.id??0];text('ammo-count',equipped?.ammo??0);text('ammo-reserve','/ '+(equipped?.reserve??0));text('reload-state',viewed.reloadUntil>s.time?'换弹中':(viewed===p?'':'观战 · ')+(weapon?.name??'手枪'));
 text('weapon-secondary',WEAPONS[0].name+' · 1');text('weapon-primary',viewed.equipment?.[1]?WEAPONS[viewed.equipment[1].id].name+' · 2':'主武器 · 空');for(const b of document.querySelectorAll('[data-weapon]')){b.classList.toggle('active',viewed.slot===Number(b.dataset.weapon));b.classList.toggle('locked',!viewed.equipment?.[Number(b.dataset.weapon)]);b.disabled=!p.alive;}
 $('#hitmarker').style.opacity=s.hit>0?1:0;$('#hurt').style.opacity=s.hurt>0?Math.min(.65,s.hurt):0;$('#crosshair').style.opacity=p.alive&&!buyOpen&&!game.camera.state.scope&&['active','planted'].includes(s.phase)?1:0;$('#scope-overlay')?.classList.toggle('hidden',!game.camera.state.scope||!p.alive||buyOpen);
 text('toast',s.toast);$('#toast').classList.toggle('show',s.toastUntil>s.time&&s.mode==='playing');
 const near=game.nearestInteraction?.(),kind=near?.type,interaction=s.interaction,progress=interaction&&interaction.actorId===p.id?interaction.progress??0:0,duration=interaction?.duration??(kind==='defuse'?5:3);text('interact-hint',near?(kind==='plant'?'按住安包 · 3 秒':kind==='defuse'?'按住拆包 · 5 秒':kind==='bomb'?'拾取炸弹':'拾取主武器'):'');const useBtn=$('#interact-button');if(useBtn){useBtn.classList.toggle('available',!!near);useBtn.querySelector('span')&&(useBtn.querySelector('span').textContent=kind==='plant'?'安包':kind==='defuse'?'拆包':'互动');useBtn.style.setProperty('--progress',`${Math.min(1,progress)*360}deg`);}const ring=$('#interaction-progress');if(ring){ring.classList.toggle('hidden',progress<=0);ring.style.setProperty('--progress',`${Math.min(1,progress)*360}deg`);text('interaction-progress',`${Math.ceil(progress*100)}%`);}
 const spec=actors.find(a=>a.id===s.spectateId);$('#spectate-hud')?.classList.toggle('hidden',p.alive||s.mode==='ready');text('spectate-name',spec?`观战 ${spec.name??'豆豆队友'}`:'等待下一回合');text('spectate-speed',`观战速度 ${s.spectateSpeed===4?'4×':'1×'}`);
 $('#touch')?.classList.toggle('hidden',buyOpen||s.mode!=='playing'||!p.alive||!['active','planted'].includes(s.phase));$('#buy-open')?.classList.toggle('hidden',s.phase!=='buy'||buyOpen||s.mode!=='playing');text('buy-status',`准备 ${Math.ceil(remaining)} 秒　资金 $ ${p.money??0}`);for(const b of document.querySelectorAll('[data-buy]')){const id=b.dataset.buy,cost=id==='armor'?600:WEAPONS[Number(id)]?.price??0;b.disabled=s.phase!=='buy'||p.money<cost||(id==='armor'&&p.armor);}
 $('#tactic-a')?.classList.toggle('active',s.tactic==='A');$('#tactic-b')?.classList.toggle('active',s.tactic==='B');map();
}
let accumulator=0,last=performance.now(),lastRender=0,manualUntil=0,perfWindow=0,frames=0,qualityTimer=0;
function step(seconds){accumulator+=Math.max(0,seconds);let limit=0;while(accumulator+1e-10>=STEP&&limit++<50000){game.update(STEP);accumulator-=STEP;}}
function render(){if(game.state.mode==='ready')game.camera.update(0,true);characterDisplay.updateBeanDisplay?.(game.player,g.camera,world,game.state.time,true);for(const actor of game.actors??game.enemies)if(actor!==game.player)characterDisplay.updateBeanDisplay?.(actor,g.camera,world,game.state.time,false);g.updateLabels?.();g.renderer.render(g.scene,g.camera);updateUI();}
function frame(now){const elapsed=Math.max(0,(now-last)/1000);last=now;if(now>manualUntil){if(!document.hidden)step(Math.min(.25,elapsed));}const interval=1000/settings.fps;if(now-lastRender>=interval-1){lastRender=now;render();frames++;}perfWindow+=elapsed;qualityTimer+=elapsed;if(mobile&&qualityTimer>5&&perfWindow>1){const actual=frames/perfWindow;if(actual<settings.fps*.78)g.setQuality(g.quality-.08);else if(actual>settings.fps*.94)g.setQuality(Math.min(.85,g.quality+.03));frames=0;perfWindow=0;qualityTimer=0;}requestAnimationFrame(frame);}
function resize(){g.resize();game.camera.update(0,game.player);updateUI(true);render();}window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);window.addEventListener('pagehide',()=>{input.reset();if(game.state.mode==='playing')game.pause();game.audio.setPlaying(false);});window.addEventListener('pageshow',()=>{last=performance.now();});
restoreSettings();settingsUI();game.reset();modeUI();updateUI(true);requestAnimationFrame(frame);
window.render_game_to_text=()=>JSON.stringify({...game.snapshot(),settings:{...settings,...input.getSensitivity(),...input.getLayout?.()},renderQuality:g.quality});
window.advanceTime=ms=>{manualUntil=performance.now()+300;step(Math.max(0,Number(ms)||0)/1000);render();};
if(new URLSearchParams(location.search).has('test'))window.__gameTest={game,g,world,input,step,render,WEAPONS,characterDisplay,setBuy,settings};
