import {THREE,C} from './gfx.js';
import {MeshBVH} from 'three-mesh-bvh';
import {findPath,DEFAULT_QUERY_FILTER,getNodeByRef} from 'navcat';
import {segmentSolid,clamp,rampHeight} from './physics.js';
import {CHARACTER} from './dimensions.js';
import {MAPS} from './maps.js';
import {shapeFor,shapeTriangles,triangleSoup} from './map-geometry.js';
import {loadNavigation} from './navigation/classic-nav.js';
import {decorateMapEnvironment} from './visual/map-environment.js';
export function createWorld(g,id='assault'){
 const solids=[],surfaces=[],bounds={},nav=new Map(),ownedGeometry=[],ownedLabels=[],ownedInstances=[],dynamic=[];let root=null,definition=null,bvh=null,bvhGeometry=null,staticSolids=[],triangleOwners=[],navigation=null;
 const api={bounds,solids,surfaces,cameraSolids:[],nav,groundAt,blocked,cameraBlocked:blocked,walkable,canWalk,path,rebuildNav,reset,solid,loadMap,dispose,areaAt,collisionCandidates,nearestDoor,interactionAt:nearestDoor,toggleDoor,damageSolid,traverse,traverseActor:traverse,stanceAt};
 function geometry(geo){ownedGeometry.push(geo);return geo;}
 function label(text,x,y,z,opts){const m=g.label(text,x,y,z,opts);root.add(m);ownedLabels.push(m);return m;}
 function solid(x,z,w,d,h,color,y=0,type='wall',material='concrete',extra={}){const q=shapeFor({x,z,w,d,h,color,y,type,material,...extra}),group=new THREE.Group();root.add(group);group.position.set(x,y,z);const mesh=g.box(0,h/2,0,w,h,d,color,group);g.decorateSurface?.(mesh,material,color,w,h);Object.assign(q,{group,initialHP:q.hp,initialOpen:q.open});solids.push(q);if(['door','grille'].includes(type)){q.dynamic=true;dynamic.push(q);}if(['floor','deck','roof','step'].includes(type))surfaces.push(q);return q;}
 function ramp(s){const q=shapeFor(s),positions=shapeTriangles(q),geo=geometry(new THREE.BufferGeometry());geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.computeVertexNormals();const normal=geo.getAttribute('normal'),uv=[];for(let i=0;i<positions.length/3;i++){const x=(positions[i*3]-q.x0)/s.w,y=(positions[i*3+1]-q.y0)/s.rise,z=(positions[i*3+2]-q.z0)/s.d;if(Math.abs(normal.getY(i))>.5)uv.push(x,z);else if(Math.abs(normal.getX(i))>.5)uv.push(z,y);else uv.push(x,y);}geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));const group=new THREE.Group();root.add(group);const m=g.mesh(geo,s.color,group);g.decorateSurface?.(m,s.material,s.color,s.w,s.d);q.group=group;solids.push(q);surfaces.push(q);}
 function batchStatic(){root.updateMatrixWorld(true);const inverse=root.matrixWorld.clone().invert(),matrix=new THREE.Matrix4(),buckets=new Map();root.traverse(m=>{if(!m.isMesh||m.isInstancedMesh||Array.isArray(m.material))return;let p=m.parent;while(p&&p!==root){if(dynamic.some(s=>s.group===p))return;p=p.parent;}const key=m.geometry.uuid+':'+m.material.uuid+':'+m.castShadow+':'+m.receiveShadow;if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(m);});for(const list of buckets.values()){if(list.length<2)continue;const first=list[0],batch=new THREE.InstancedMesh(first.geometry,first.material,list.length);batch.name='static-map-batch';batch.castShadow=first.castShadow;batch.receiveShadow=first.receiveShadow;list.forEach((m,i)=>{batch.setMatrixAt(i,matrix.multiplyMatrices(inverse,m.matrixWorld));m.removeFromParent();});batch.instanceMatrix.needsUpdate=true;batch.computeBoundingSphere();root.add(batch);ownedInstances.push(batch);}}
 function buildBVH(){staticSolids=solids.filter(s=>!s.dynamic);const soup=triangleSoup(staticSolids);triangleOwners=soup.triSolids;bvhGeometry=geometry(new THREE.BufferGeometry());bvhGeometry.setAttribute('position',new THREE.Float32BufferAttribute(soup.positions,3));bvh=new MeshBVH(bvhGeometry,{indirect:true,targetLeafSize:12});api.bvh=bvh;}
 function dispose(){bvh=null;bvhGeometry=null;staticSolids=[];triangleOwners=[];dynamic.length=0;for(const m of ownedInstances)m.dispose();ownedInstances.length=0;if(root)root.removeFromParent();for(const l of ownedLabels){const i=g.labels?.indexOf(l);if(i>=0)g.labels.splice(i,1);l.material?.map?.dispose();l.material?.dispose();}ownedLabels.length=0;for(const geo of ownedGeometry)geo.dispose();ownedGeometry.length=0;solids.length=surfaces.length=0;nav.clear();root=null;navigation=null;api.navigation=null;api.bvh=null;}
 function loadMap(id){const next=MAPS.find(m=>m.id===id);if(!next)throw new Error(`Unknown map: ${id}`);dispose();definition=next;g.environment?.(id);root=new THREE.Group();root.name='map:'+id;g.scene.add(root);Object.assign(bounds,next.bounds);Object.assign(api,{id:next.id,name:next.name,mode:next.mode,metadata:{id:next.id,name:next.name,mode:next.mode,bounds,checklist:next.checklist},sites:next.sites.map(p=>({...p})),spawns:next.spawns,routes:next.routes,routeVariants:next.routeVariants,defensePositions:next.defensePositions,defenseByTactic:next.defenseByTactic,postPlantPositions:next.postPlantPositions,areas:next.areas,tactics:next.tactics,hostageSpawns:next.hostagePositions,hostagePositions:next.hostagePositions,rescueZones:next.rescueZones,ladders:next.ladders,lowZones:next.lowZones,spawn:next.spawns.attack[0]});
  const w=bounds.x1-bounds.x0,d=bounds.z1-bounds.z0,cx=(bounds.x0+bounds.x1)/2,cz=(bounds.z0+bounds.z1)/2;
  const backdrop=g.mesh(geometry(new THREE.PlaneGeometry(500,500)),next.mode==='rescue'?0x8a9b9d:0xd6bb91,root);backdrop.rotation.x=-Math.PI/2;backdrop.position.y=-3;backdrop.castShadow=false;
  solid(cx,cz,w,d,2,next.colors.floor,-2,'floor',next.mode==='rescue'?'concrete':'sand');
  for(const [x,z,ww,dd] of [[bounds.x0,cz,.6,d],[bounds.x1,cz,.6,d],[cx,bounds.z0,w,.6],[cx,bounds.z1,w,.6]])solid(x,z,ww,dd,10,next.colors.boundary,0,'boundary',next.mode==='rescue'?'brick':'stone');
  for(const s of next.terrain){if(s.type==='ramp')ramp(s);else solid(s.x,s.z,s.w,s.d,s.h,s.color,s.y||0,s.type,s.material,s);}
  // Decorative detail is cheap and cannot alter tactical collision or LOS.
  if(id==='assault'){for(const z of [-18,-8,2,12]){g.box(-23.55,3.3,z,.12,6.6,.18,0x566974,root);g.box(23.55,3.3,z,.12,6.6,.18,0x566974,root);}for(const x of [-17,-7,3,13]){g.box(x,6.42,-2,.17,.2,38,0x3f515e,root);g.box(x,6.15,1,2,.12,.4,0xffe7aa,root);}for(const x of [-21,-12,-3,6,15])g.box(x,.018,34,.08,.012,4,0xe6d9ad,root);for(const l of next.ladders){for(let y=l.y0+.25;y<l.y1;y+=.35)g.box(l.x,y,l.z,1,.08,.13,0xc0c9ca,root);g.box(l.x-.48,(l.y0+l.y1)/2,l.z,.08,l.y1-l.y0,.08,0x576874,root);g.box(l.x+.48,(l.y0+l.y1)/2,l.z,.08,l.y1-l.y0,.08,0x576874,root);}}
  else{for(const [x,z] of [[-38,-30],[42,-33],[43,28],[-43,27]]){g.box(x,3,z,1,6,1,0xbaa077,root);g.box(x,6.15,z,1.5,.3,1.5,0xd6bb90,root);}for(const x of [-36,-24])g.box(x,5.6,16,.4,.5,23,0xa38a69,root);for(const [x,z,y] of [[31,-25,3.23],[-33,-24,.53]]){g.box(x,y,z,6,.025,6,0xb57545,root);}}
  decorateMapEnvironment(g,root,next);
  for(const site of api.sites){if(api.mode!=='bomb')continue;const ring=g.mesh(geometry(new THREE.TorusGeometry(site.radius,.045,5,48)),site.color,root);ring.rotation.x=-Math.PI/2;ring.position.set(site.x,site.y+.045,site.z);label(site.id,site.x,site.y+3.2,site.z,{size:.6});}
  for(const zone of next.rescueZones){const ring=g.mesh(geometry(new THREE.TorusGeometry(zone.radius,.065,5,48)),0x6da896,root);ring.rotation.x=-Math.PI/2;ring.position.set(zone.x,.05,zone.z);label('救援区',zone.x,3.4,zone.z,{size:.55});}
  for(const area of next.areas)label(area.name,area.x,(area.y||0)+3,area.z,{size:.35});
  batchStatic();buildBVH();g.fitBounds?.(bounds);rebuildNav();return api;
 }
 function reset(){for(const s of dynamic){s.active=true;s.hp=s.initialHP;s.open=s.initialOpen??false;s.group.visible=true;if(s.type==='door')setDoor(s,s.open);}api.navigationRevision=(api.navigationRevision||0)+1;}
 function setDoor(s,open){s.open=!!open;s.active=!s.open;s.group.visible=!s.open;api.navigationRevision=(api.navigationRevision||0)+1;return s.open;}
 function toggleDoor(id){const s=dynamic.find(s=>s.type==='door'&&s.id===id);return s?setDoor(s,!s.open):false;}
 function nearestDoor(a){let best=null,distance=2.2;for(const s of dynamic){if(s.type!=='door')continue;const p={x:(s.x0+s.x1)/2,y:s.y0+Math.min(a.height*.5,1.1),z:(s.z0+s.z1)/2},d=Math.hypot(a.x-p.x,a.z-p.z);if(d>=distance||Math.abs(a.y-s.y0)>1)continue;const hit=blocked({x:a.x,y:a.y+Math.min(a.height*.7,1.1),z:a.z},p);if(hit&&hit.solid!==s)continue;best={type:'door',id:s.id,solid:s,open:s.open,label:s.open?'关门':'开门',x:p.x,y:s.y0,z:p.z};distance=d;}return best;}
 function damageSolid(s,damage){if(!s?.active||s.type!=='grille')return false;s.hp-=damage;if(s.hp<=0){s.active=false;s.group.visible=false;api.navigationRevision=(api.navigationRevision||0)+1;return true;}return false;}
 function groundAt(x,z,maxY=Infinity){if(x<bounds.x0||x>bounds.x1||z<bounds.z0||z>bounds.z1)return null;let h=0;for(const s of solids){if(!s.active||x<s.x0||x>s.x1||z<s.z0||z>s.z1)continue;const y=s.shape==='ramp'?rampHeight(s,x,z):s.y1;if(y<=maxY+.001)h=Math.max(h,y);}return h;}
 const queryBox=new THREE.Box3(),ray=new THREE.Ray(),direction=new THREE.Vector3(),start=new THREE.Vector3();
 function collisionCandidates(x,z,dx,dz,y,height,radius){const found=new Set();queryBox.min.set(Math.min(x,x+dx)-radius-.02,y-.4,Math.min(z,z+dz)-radius-.02);queryBox.max.set(Math.max(x,x+dx)+radius+.02,y+height+.05,Math.max(z,z+dz)+radius+.02);bvh?.shapecast({intersectsBounds:b=>b.intersectsBox(queryBox),intersectsTriangle:(_t,index)=>{const s=staticSolids[triangleOwners[index]];if(s)found.add(s);return false;}});for(const s of dynamic)if(s.active&&s.x1>=queryBox.min.x&&s.x0<=queryBox.max.x&&s.z1>=queryBox.min.z&&s.z0<=queryBox.max.z)found.add(s);return [...found];}
 function blocked(a,b,pad=0){let best=null;const length=Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);if(pad===0&&length>1e-8){start.set(a.x,a.y,a.z);direction.set(b.x-a.x,b.y-a.y,b.z-a.z).divideScalar(length);ray.set(start,direction);const hit=bvh?.raycastFirst(ray,THREE.DoubleSide,0,length);if(hit){const solid=staticSolids[triangleOwners[hit.faceIndex]];best={t:hit.distance/length,normal:hit.face.normal.clone(),solid};}for(const s of collisionCandidates(a.x,a.z,0,0,a.y,.001,.001)){if(s.dynamic)continue;const h=segmentSolid(a,b,s);if(h?.t===0){best={...h,solid:s};break;}}}else for(const s of staticSolids){const h=segmentSolid(a,b,s,pad);if(h&&(!best||h.t<best.t))best={...h,solid:s};}for(const s of dynamic){if(!s.active)continue;const h=segmentSolid(a,b,s,pad);if(h&&(!best||h.t<best.t))best={...h,solid:s};}return best;}
 function stanceAt(p){return api.lowZones?.some(q=>p.x>=q.x0&&p.x<=q.x1&&p.z>=q.z0&&p.z<=q.z1&&p.y>=q.y0-.15&&p.y<=q.y1)?'crouch':'stand';}
 function clearAt(x,z,y,radius=CHARACTER.navRadius,profile='soldier',ignoreDynamic=false){const low=stanceAt({x,y,z})==='crouch';if(profile==='hostage'&&low)return false;const height=low?.88:CHARACTER.height;if(x-radius<bounds.x0||x+radius>bounds.x1||z-radius<bounds.z0||z+radius>bounds.z1)return false;for(const s of collisionCandidates(x,z,0,0,y,height,radius)){if(!s.active||(ignoreDynamic&&s.dynamic)||s.y0>=y+height-.001)continue;if(s.shape==='ramp'){if(x<s.x0-radius||x>s.x1+radius||z<s.z0-radius||z>s.z1+radius)continue;const top=rampHeight(s,clamp(x,s.x0,s.x1),clamp(z,s.z0,s.z1));if(top>y+.38)return false;continue;}if(s.y1<=y+.38)continue;if(x>s.x0-radius&&x<s.x1+radius&&z>s.z0-radius&&z<s.z1+radius)return false;}return true;}
 function floorsAt(x,z){const result=[0];for(const s of surfaces){if(s.type==='floor'||!s.active||x<s.x0||x>s.x1||z<s.z0||z>s.z1)continue;const y=s.shape==='ramp'?rampHeight(s,x,z):s.y1;if(!result.some(v=>Math.abs(v-y)<.04))result.push(y);}return result.sort((a,b)=>a-b);}
 function walkable(x,z,maxY=.38){const choices=floorsAt(x,z).filter(h=>h<=maxY+.001&&clearAt(x,z,h));return choices.length?Math.max(...choices):null;}
 function canWalk(a,b,radius=CHARACTER.navRadius,opts={}){let h=groundAt(a.x,a.z,(a.y??0)+.38);if(h===null||Math.abs(h-(a.y??h))>.38)return false;const n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/.2));for(let i=0;i<=n;i++){const t=i/n,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t,next=groundAt(x,z,h+.38);if(next===null||Math.abs(next-h)>.38||!clearAt(x,z,next,radius,opts.profile||'soldier',opts.ignoreDynamic))return false;h=next;}return Math.abs(h-(b.y??0))<=.38;}
 function rebuildNav(){navigation=loadNavigation(api.id);api.navigation=navigation;nav.clear();for(const node of navigation.soldier.mesh.nodes){if(!node?.allocated)continue;const tile=navigation.soldier.mesh.tiles[node.tileId],poly=tile?.polys[node.polyIndex];if(!poly)continue;let x=0,y=0,z=0;for(const index of poly.vertices){x+=tile.vertices[index*3];y+=tile.vertices[index*3+1];z+=tile.vertices[index*3+2];}const n=poly.vertices.length;x/=n;y/=n;z/=n;y=groundAt(x,z,y+.16)??y;nav.set(node.ref,{...node,x,y,z,id:node.ref,neighbors:[]});}api.navigationRevision=(api.navigationRevision||0)+1;}
 function path(from,to,{profile='soldier'}={}){if(canWalk(from,to,CHARACTER.navRadius,{profile}))return [{...to,y:to.y??0,kind:stanceAt(to)==='crouch'?'low':'walk',action:stanceAt(to)==='crouch'?'low':'walk'}];const mesh=navigation[profile]?.mesh;if(!mesh)return [];const result=findPath(mesh,[from.x,from.y??0,from.z],[to.x,to.y??0,to.z],[1.8,.45,1.8],DEFAULT_QUERY_FILTER);if(!result.success||!(result.flags&2))return [];const points=[];for(const point of result.path){const [x,rawY,z]=point.position,y=groundAt(x,z,rawY+.16)??rawY,p={x,y,z,kind:stanceAt({x,y,z})==='crouch'?'low':'walk'};if(profile==='hostage'&&p.kind==='low')return [];if(point.flags&2){const node=getNodeByRef(mesh,point.nodeRef),link=navigation[profile].links.find(l=>l.id===node.offMeshConnectionId),ladder=api.ladders.find(l=>l.id===link?.ladderId);if(ladder){p.kind='ladder';p.ladderId=ladder.id;}}p.action=p.kind;points.push(p);}for(let i=0;i<points.length-1;i++)if(points[i].kind==='ladder'){const id=points[i].ladderId;points[i].kind=points[i].action='walk';points[i+1].kind=points[i+1].action='ladder';points[i+1].ladderId=id;points[i+1].targetY=points[i+1].y;i++;}if(points.length&&Math.hypot(points[0].x-from.x,points[0].z-from.z)<.12&&Math.abs(points[0].y-from.y)<.2)points.shift();
 const last=points.at(-1);if(last&&Math.hypot(last.x-to.x,last.z-to.z)>.08&&canWalk(last,to,CHARACTER.navRadius,{profile,ignoreDynamic:true}))points.push({...to,y:to.y??last.y,kind:stanceAt(to)==='crouch'?'low':'walk',action:stanceAt(to)==='crouch'?'low':'walk'});
 // Door and grille are omitted during baking but inserted into traversal paths.
 const output=[];let previous=from;for(const point of points){for(const s of dynamic){if(!s.active)continue;const h=segmentSolid({x:previous.x,y:previous.y+.6,z:previous.z},{x:point.x,y:point.y+.6,z:point.z},s,.08);if(h){const t=Math.max(0,h.t-.2/Math.max(.1,Math.hypot(point.x-previous.x,point.z-previous.z)));output.push({x:previous.x+(point.x-previous.x)*t,y:previous.y,z:previous.z+(point.z-previous.z)*t,kind:s.type==='door'?'door':'grille',action:s.type==='door'?'door':'grille',id:s.id,solid:s});}}output.push(point);previous=point;}return output;
 }
 function traverse(actor,dt,{x=actor.vx,z=actor.vz,jump=actor.traverseJump||false,waypoint=actor.traverseWaypoint}={}){if(actor.isHostage||actor.navigationProfile==='hostage'){actor.crouched=false;actor.stance='stand';actor.height=CHARACTER.height;actor.eye=CHARACTER.eye;return false;}const low=stanceAt(actor)==='crouch';actor.crouched=low;actor.stance=low?'crouch':'stand';actor.height=low?.88:CHARACTER.height;actor.eye=low?.72:CHARACTER.eye;if(low){const speed=Math.hypot(actor.vx,actor.vz);if(speed>2.2){actor.vx*=2.2/speed;actor.vz*=2.2/speed;}}if(jump){actor.ladderId=null;actor.ladderCooldown=.45;}actor.ladderCooldown=Math.max(0,(actor.ladderCooldown||0)-dt);if(actor.ladderCooldown>0)return false;const desired=waypoint?.kind==='ladder'?api.ladders.find(l=>l.id===waypoint.ladderId):null;let ladder=api.ladders.find(l=>l.id===actor.ladderId)||desired;const forward=actor.traverseForward??Math.hypot(x||0,z||0);if(!ladder&&Math.abs(forward)>.1)ladder=api.ladders.find(l=>Math.hypot(actor.x-l.x,actor.z-l.z)<1.05&&actor.y>=l.y0-.1&&actor.y<=l.y1+.15);if(!ladder)return false;if(!actor.ladderId&&Math.min(Math.hypot(actor.x-ladder.bottom.x,actor.z-ladder.bottom.z),Math.hypot(actor.x-ladder.exit.x,actor.z-ladder.exit.z))>1.45)return false;const atLower=actor.y<ladder.y0+.2;if(desired&&atLower&&Math.hypot(actor.x-ladder.bottom.x,actor.z-ladder.bottom.z)>1.5)return false;if(!actor.ladderId&&Math.abs(forward)<.1)return false;actor.ladderId=ladder.id;let direction=waypoint?Math.sign((waypoint.targetY??waypoint.y)-actor.y):Math.sign(forward);actor.vx=actor.vz=actor.vy=0;actor.grounded=false;actor.x=ladder.x;actor.z=ladder.z;actor.y=clamp(actor.y+direction*2.8*dt,ladder.y0,ladder.y1);if(direction>0&&actor.y>=ladder.y1){actor.x=ladder.exit.x;actor.z=ladder.exit.z;actor.y=ladder.exit.y;actor.ladderId=null;actor.ladderCooldown=.5;actor.grounded=true;}else if(direction<0&&actor.y<=ladder.y0){actor.x=ladder.bottom.x;actor.z=ladder.bottom.z;actor.y=ladder.bottom.y;actor.ladderId=null;actor.ladderCooldown=.5;actor.grounded=true;}return true;}
 function areaAt(p){let best=null,d=Infinity;for(const a of api.areas){const n=Math.hypot(p.x-a.x,p.z-a.z,2*(p.y-(a.y||0)));if(n<d){d=n;best=a;}}return best?.name||api.name;}
 loadMap(id);return api;
}
